# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matTimesVec <- function(mat, v) {
    .Call(`_logreg2ph_matTimesVec`, mat, v)
}

matDivideVec <- function(mat, v) {
    .Call(`_logreg2ph_matDivideVec`, mat, v)
}

lengthenWT <- function(w_t_original, n, modifyW_T = TRUE) {
    .Call(`_logreg2ph_lengthenWT`, w_t_original, n, modifyW_T)
}

calculateMu <- function(design_mat, prev) {
    .Call(`_logreg2ph_calculateMu`, design_mat, prev)
}

calculateGradient <- function(w_t, n, design_mat, Y_col, muVector, modifyW_T = FALSE) {
    .Call(`_logreg2ph_calculateGradient`, w_t, n, design_mat, Y_col, muVector, modifyW_T)
}

calculateHessian <- function(design_mat, w_t, muVector, n, mus, modifyW_T = FALSE) {
    .Call(`_logreg2ph_calculateHessian`, design_mat, w_t, muVector, n, mus, modifyW_T)
}

pYstarCalc <- function(gamma_design_mat, n, excludeRows, prev_gamma, comp_dat_all, Y_unval_index, pYstar, mu_gamma) {
    .Call(`_logreg2ph_pYstarCalc`, gamma_design_mat, n, excludeRows, prev_gamma, comp_dat_all, Y_unval_index, pYstar, mu_gamma)
}

pXCalc <- function(n, comp_dat_all_cropped, errorsX, errorsY, pX, prevRows) {
    .Call(`_logreg2ph_pXCalc`, n, comp_dat_all_cropped, errorsX, errorsY, pX, prevRows)
}

